### ISSUE TITLE
KDE tittle bar buttons overwritten.

### ISSUE THREAD

**Issue by githubtefo** [PapirusDevelopmentTeam/firefox-papirus-icon-theme#1]
Hi!
Thanks again for the quick and nice development of this theme!
I am trying on my KDE session and it looks beautiful. Although I am observing some overlapping on the tittle bar buttons (please see below).
![Screenshot_20210620_232002](https://user-images.githubusercontent.com/11220103/122783034-35c95a80-d27f-11eb-931d-692df57ceba9.png)

**Comment by githubtefo** [comment]
I erased all this section from _~/.mozilla/firefox/YOURPROFILE.default/chrome/firefox-papirus-icon-theme/theme/icons.css_ and the overlap is gone!
`/* Window buttons */
:root[tabsintitlebar] #titlebar .titlebar-buttonbox .titlebar-close .toolbarbutton-icon {
	list-style-image: url("icons/window-close-symbolic.svg") !important;
}
:root[tabsintitlebar] #titlebar .titlebar-buttonbox .titlebar-max .toolbarbutton-icon {
	list-style-image: url("icons/window-maximize-symbolic.svg") !important;
}
:root[tabsintitlebar] #titlebar .titlebar-buttonbox .titlebar-restore .toolbarbutton-icon {
	list-style-image: url("icons/window-restore-symbolic.svg") !important;
}
:root[tabsintitlebar] #titlebar .titlebar-buttonbox .titlebar-min .toolbarbutton-icon {
	list-style-image: url("icons/window-minimize-symbolic.svg") !important;
}
:root[tabsintitlebar][inFullscreen] #window-controls #restore-button .toolbarbutton-icon {
	list-style-image: url("icons/view-restore-symbolic.svg") !important;
}`

**Comment by varlesh** [comment]
Thx for info, i'm comment this section

**Comment by githubtefo** [comment]
Good! Thank you! Looks awesome.
